---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
useGitignore: true

dictionaryDefinitions:
  - name: cspell-words
    path: './cspell-words.txt'
    addWords: true

dictionaries:
  - cspell-words
  - python
  - typescript

language: en-US, de-DE

import:
  - '@cspell/dict-de-de'

ignorePaths:
  - '.*'
  - 'cspell.config.yaml'
  - 'dist'
  - 'LICENSE'
  - 'node_modules'
  - 'package*.json'
  - 'pnpm-lock.yaml'
  - 'uv.lock'
