[global]

[logger]
level = "info"
messageFormat = "%(asctime)s	%(levelname)s	%(name)s	%(message)s"

[client]
showErrorDetails = "full"

[runner]
fastReruns = true

[server]
port = 8503
maxUploadSize = 1
fileWatcherType = "none"
baseUrlPath = "/korrekturleser-streamlit"

[browser]
gatherUsageStats = false

[mapbox]

[theme]

[secrets]
